ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2026 1 17 1 34 3)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright © Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "STM32F1_1_N"
    (originalName "STM32F1_1_N")
    (pin (pinNum 1)  (pt 400 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 400 -650) "1" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 400 -800) "3V3" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 500 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 500 -650) "2" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -800) "GND" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 600 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 600 -650) "3" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -800) "5V" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 700 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 700 -650) "4" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 700 -800) "B9" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 800 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 800 -650) "5" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 800 -800) "B8" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 900 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 900 -650) "6" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -800) "B7" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 1000 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1000 -650) "7" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -800) "B6" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 1100 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -650) "8" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -800) "B5" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 1200 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -650) "9" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1200 -800) "B4" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 1300 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1300 -650) "10" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1300 -800) "B3" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 1400 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 -650) "11" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1400 -800) "A15" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 1500 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1500 -650) "12" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 -800) "A12" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 1600 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1600 -650) "13" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1600 -800) "A11" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 1700 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1700 -650) "14" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1700 -800) "A10" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 1800 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1800 -650) "15" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1800 -800) "A9" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 1900 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1900 -650) "16" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1900 -800) "A8" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 2000 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2000 -650) "17" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2000 -800) "B15" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 2100 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2100 -650) "18" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2100 -800) "B14" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt 2200 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2200 -650) "19" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2200 -800) "B13" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 2300 -800) (rotation 90.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2300 -650) "20" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2300 -800) "B12" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 21)  (pt 400 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 400 -1450) "40" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 400 -1300) "VB" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 22)  (pt 500 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 500 -1450) "39" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 500 -1300) "C13" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 23)  (pt 600 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 600 -1450) "38" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -1300) "C14" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 24)  (pt 700 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 700 -1450) "37" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 700 -1300) "C15" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 25)  (pt 800 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 800 -1450) "36" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 800 -1300) "A0" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 26)  (pt 900 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 900 -1450) "35" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -1300) "A1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 27)  (pt 1000 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1000 -1450) "34" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1000 -1300) "A2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 28)  (pt 1100 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1100 -1450) "33" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1300) "A3" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 29)  (pt 1200 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1450) "32" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1200 -1300) "A4" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 30)  (pt 1300 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1300 -1450) "31" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1300 -1300) "A5" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 31)  (pt 1400 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 -1450) "30" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1400 -1300) "A6" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 32)  (pt 1500 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1500 -1450) "29" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 -1300) "A7" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 33)  (pt 1600 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1600 -1450) "28" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1600 -1300) "B0" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 34)  (pt 1700 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1700 -1450) "27" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1700 -1300) "B1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 35)  (pt 1800 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1800 -1450) "26" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1800 -1300) "B10" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 36)  (pt 1900 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1900 -1450) "25" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1900 -1300) "B11" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 37)  (pt 2000 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2000 -1450) "24" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2000 -1300) "R" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 38)  (pt 2100 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2100 -1450) "23" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2100 -1300) "3V3" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 39)  (pt 2200 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2200 -1450) "22" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2200 -1300) "GND" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 40)  (pt 2300 -1300) (rotation 270.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2300 -1450) "21" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2300 -1300) "GND" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 300 -1300) (pt 300 -800) (width 10) )
    (line (pt 300 -1300) (pt 2400 -1300) (width 10) )
    (line (pt 300 -800) (pt 2400 -800) (width 10) )
    (line (pt 2400 -800) (pt 2400 -1300) (width 10) )
    (attr "RefDes" ""  (pt 2400 -900) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 2400 -1000) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "TB6612_1_N"
    (originalName "TB6612_1_N")
    (pin (pinNum 1)  (pt 300 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 300 450) "VM" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 400) "VM" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 200 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 200 450) "VCC" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 400) "VCC" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 100 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 100 450) "GND" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 400) "GND" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 0 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 0 450) "A01" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 400) "A01" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -100 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -100 450) "A02" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -100 400) "A02" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt -200 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -200 450) "B02" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -200 400) "B02" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt -300 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -300 450) "B01" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 400) "B01" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt -400 400) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -400 450) "GND" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -400 400) "GND" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 300 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 300 -150) "PWMA" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -100) "PWMA" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 200 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 200 -150) "AIN2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -100) "AIN2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 100 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 100 -150) "AIN1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 -100) "AIN1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 0 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 0 -150) "STBY" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "STBY" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt -100 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -100 -150) "BIN1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -100 -100) "BIN1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt -200 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -200 -150) "BIN2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -200 -100) "BIN2" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt -300 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -300 -150) "PWMB" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 -100) "PWMB" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt -400 -100) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -400 -150) "GND" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -400 -100) "GND" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -500 -100) (pt -500 400) (width 10) )
    (line (pt -500 -100) (pt 400 -100) (width 10) )
    (line (pt -500 400) (pt 400 400) (width 10) )
    (line (pt 400 400) (pt 400 -100) (width 10) )
    (attr "RefDes" ""  (pt 400 300) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 400 200) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "MP1584EN_1_N"
    (originalName "MP1584EN_1_N")
    (pin (pinNum 1)  (pt 600 300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 750 300) "5" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 300) "+IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 600 200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 750 200) "6" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 200) "+IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 600 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 750 -100) "7" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -100) "-IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 600 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 750 -200) "8" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 600 -200) "-IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -300 300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 300) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 300) "+OUT" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt -300 200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 200) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 200) "+OUT" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt -300 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -100) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 -100) "-OUT" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt -300 -200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -200) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 -200) "-OUT" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -300 -300) (pt -300 400) (width 10) )
    (line (pt -300 -300) (pt 600 -300) (width 10) )
    (line (pt -300 400) (pt 600 400) (width 10) )
    (line (pt 600 400) (pt 600 -300) (width 10) )
    (attr "RefDes" ""  (pt -300 400) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -300 -400) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Encoder_1_N"
    (originalName "Encoder_1_N")
    (pin (pinNum 1)  (pt -600 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 100) "M1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 100) "M1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -600 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 0) "GND" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 0) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -600 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -100) "C1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -100) "C1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt -600 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -200) "C2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -200) "C2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -600 -300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -300) "VCC" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -300) "VCC" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt -600 -400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -400) "M2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -600 -400) "M2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -800 -500) (pt -800 200) (width 10) )
    (line (pt -800 -500) (pt -600 -500) (width 10) )
    (line (pt -800 200) (pt -600 200) (width 10) )
    (line (pt -600 200) (pt -600 -500) (width 10) )
    (attr "RefDes" ""  (pt -800 200) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -800 -600) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Pin6x_1_N"
    (originalName "Pin6x_1_N")
    (pin (pinNum 1)  (pt -300 300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 300) "VCC" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 300) "VCC" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -300 200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 200) "GND" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 200) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -300 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 100) "SCL" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 100) "SCL" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt -300 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 0) "SDA" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 0) "SDA" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -300 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -100) "GPL01" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 -100) "GPI01" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt -300 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -200) "XSHUT" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 -200) "XSHUT" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -400 -300) (pt -400 400) (width 10) )
    (line (pt -400 -300) (pt -300 -300) (width 10) )
    (line (pt -400 400) (pt -300 400) (width 10) )
    (line (pt -300 400) (pt -300 -300) (width 10) )
    (attr "RefDes" ""  (pt -400 400) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -400 -400) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Pin4x_1_N"
    (originalName "Pin4x_1_N")
    (pin (pinNum 1)  (pt -300 300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 300) "1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 300) "5V" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -300 200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 200) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 200) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -300 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 100) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 100) "RX" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt -300 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 0) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 0) "TX" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -400 -100) (pt -400 400) (width 10) )
    (line (pt -400 -100) (pt -300 -100) (width 10) )
    (line (pt -400 400) (pt -300 400) (width 10) )
    (line (pt -300 400) (pt -300 -100) (width 10) )
    (attr "RefDes" ""  (pt -400 400) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -400 -200) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Pin_1_N"
    (originalName "Pin_1_N")
    (pin (pinNum 1)  (pt -300 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 100) "1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 100) "IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -300 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 0) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 0) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -600 -100) (pt -600 200) (width 10) )
    (line (pt -600 -100) (pt -300 -100) (width 10) )
    (line (pt -600 200) (pt -300 200) (width 10) )
    (line (pt -300 200) (pt -300 -100) (width 10) )
    (attr "RefDes" ""  (pt -600 200) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -600 -200) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Switch_1_N"
    (originalName "Switch_1_N")
    (pin (pinNum 1)  (pt 300 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 450 100) "1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 100) "IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 300 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 450 0) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 0) "IN" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 300 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 450 -100) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 300 -100) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -200) (pt 0 200) (width 10) )
    (line (pt 0 -200) (pt 300 -200) (width 10) )
    (line (pt 0 200) (pt 300 200) (width 10) )
    (line (pt 300 200) (pt 300 -200) (width 10) )
    (attr "RefDes" ""  (pt 0 200) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 0 -300) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "ECA1CHG471B_1_N"
    (originalName "ECA1CHG471B_1_N")
    (pin (pinNum 1)  (pt 0 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 0) "P" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 0) "P" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 0) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 0) "N" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "N" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -46.181 -60.315) (pt -46.181 -55.315) (width 10) )
    (line (pt -46.181 -60.315) (pt -11.181 -60.315) (width 10) )
    (line (pt -46.181 -55.315) (pt -11.181 -55.315) (width 10) )
    (line (pt -11.181 -55.315) (pt -11.181 -60.315) (width 10) )
    (line (pt -31.181 -75.315) (pt -31.181 -40.315) (width 10) )
    (line (pt -31.181 -75.315) (pt -26.181 -75.315) (width 10) )
    (line (pt -31.181 -40.315) (pt -26.181 -40.315) (width 10) )
    (line (pt -26.181 -40.315) (pt -26.181 -75.315) (width 10) )
    (line (pt 20 100) (pt 20 0) (width 10) )
    (line (pt 20 0) (pt 20 -100) (width 10) )
    (line (pt 0 0) (pt 20 0) (width 10) )
    (line (pt 100 0) (pt 60 0) (width 10) )
    (arc (pt 232.815 0) (radius 174.345) (startAngle 145) (sweepAngle 70) (width 10))
    (attr "RefDes" ""  (pt -46.181 -210) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -120 110) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Price" "None"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MF" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MP" "ECA1CHG471B"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Availability" "Unavailable"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Package" "None"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "SR211C104KARTR1_1_N"
    (originalName "SR211C104KARTR1_1_N")
    (pin (pinNum 1)  (pt 0 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt -50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 100 0) (rotation 0.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 150 0) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -75.073) (pt 0 75) (width 10) )
    (line (pt 0 -75.073) (pt 25 -75.073) (width 10) )
    (line (pt 0 75) (pt 25 75) (width 10) )
    (line (pt 25 75) (pt 25 -75.073) (width 10) )
    (line (pt 75.073 -75.073) (pt 75.073 75) (width 10) )
    (line (pt 75.073 -75.073) (pt 100 -75.073) (width 10) )
    (line (pt 75.073 75) (pt 100 75) (width 10) )
    (line (pt 100 75) (pt 100 -75.073) (width 10) )
    (attr "RefDes" ""  (pt 0 75) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 0 -175.073) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Package" "Radial AVX Interconnect / Elco"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MF" "AVX"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MP" "SR211C104KARTR1"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "SW4_1_N"
    (originalName "SW4_1_N")
    (pin (pinNum 1)  (pt -200 100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -300 100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -200 100) "" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 200 100) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 300 100) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 100) "" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -200 0) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt -300 0) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -200 0) "" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 200 0) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 300 0) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 0) "" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (arc (pt 130 50) (radius 20) (startAngle 348.873) (sweepAngle 354.392) (width 10))
    (line (pt -150 100) (pt -150 120) (width 10) )
    (line (pt -150 100) (pt 150 100) (width 10) )
    (line (pt -150 120) (pt 150 120) (width 10) )
    (line (pt 150 120) (pt 150 100) (width 10) )
    (line (pt -60 120) (pt -60 160) (width 10) )
    (line (pt -60 120) (pt 60 120) (width 10) )
    (line (pt -60 160) (pt 60 160) (width 10) )
    (line (pt 60 160) (pt 60 120) (width 10) )
    (line (pt 150 50) (pt 200 50) (width 10) )
    (line (pt 200 50) (pt 200 100) (width 10) )
    (line (pt 200 0) (pt 200 50) (width 10) )
    (line (pt -150 50) (pt -200 50) (width 10) )
    (line (pt -200 50) (pt -200 100) (width 10) )
    (line (pt -200 0) (pt -200 50) (width 10) )
    (arc (pt -130 50) (radius 20) (startAngle 348.873) (sweepAngle 354.392) (width 10))
    (attr "RefDes" ""  (pt -210 160) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -210 -130) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Value" "Button chip 4 pin"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "GND_1_N"
    (originalName "GND_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 110 100) (pt 110 -100) (width 15) )
    (line (pt 140 70) (pt 140 -70) (width 15) )
    (line (pt 170 40) (pt 170 -40) (width 15) )
    (line (pt 200 10) (pt 200 -10) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (compDef "STM32F1"
    (originalName "STM32F1")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "STM32F1_1_N") )
    (attachedPattern (patternNum 1) (patternName "STM32F1")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "TB6612"
    (originalName "TB6612")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "TB6612_1_N") )
    (attachedPattern (patternNum 1) (patternName "TB6612")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "MP1584EN"
    (originalName "MP1584EN")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "MP1584EN_1_N") )
    (attachedPattern (patternNum 1) (patternName "MP1584EN")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "ENCODER"
    (originalName "ENCODER")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "Encoder_1_N") )
    (attachedPattern (patternNum 1) (patternName "ENCODER")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "PIN6X"
    (originalName "PIN6X")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "Pin6x_1_N") )
    (attachedPattern (patternNum 1) (patternName "PIN6X")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "PIN4X"
    (originalName "PIN4X")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "Pin4x_1_N") )
    (attachedPattern (patternNum 1) (patternName "PIN4X")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "PIN"
    (originalName "PIN")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "Pin_1_N") )
    (attachedPattern (patternNum 1) (patternName "PIN")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "SWITCH"
    (originalName "SWITCH")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "Switch_1_N") )
    (attachedPattern (patternNum 1) (patternName "SWITCH")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "ECA1CHG471B"
    (originalName "ECA1CHG471B")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "ECA1CHG471B_1_N") )
    (attachedPattern (patternNum 1) (patternName "CAPPRD500W60D800H1150")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "SR211C104KARTR1"
    (originalName "SR211C104KARTR1")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "SR211C104KARTR1_1_N") )
    (attachedPattern (patternNum 1) (patternName "CAPRR508W50L508T317H508")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "SW4"
    (originalName "SW4")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 0)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "SW4_1_N") )
    (attachedPattern (patternNum 1) (patternName "SW4")
      (numPads 0)
      (padPinMap
      )
    )
  )
  (compDef "GND"
    (originalName "GND")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "GND") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "GND_1_N") )
  )
)

(netlist "Netlist_1"
)

(schematicDesign "SchDesign_1"
  (schDesignHeader
    (workspaceSize 9500 7500)
    (gridDfns
      (grid "100mil")
    )
    (designInfo
      (fieldSet "(Default)"
        (fieldDef "Time" "")
        (fieldDef "Date" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Author" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Organization" "")
        (fieldDef "Address1" "")
        (fieldDef "Address2" "")
        (fieldDef "Address3" "")
        (fieldDef "Address4" "")
        (fieldDef "Title" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Revision" "")
        (fieldDef "Rule" "")
        (fieldDef "ImagePath" "")
        (fieldDef "ProjectName" "")
        (fieldDef "Application_BuildNumber" "")
      )
    )
    (refPointSize 100)
    (infoPointSize 100)
    (junctionSize 20)
    (refPointSizePrint 100)
    (infoPointSizePrint 100)
    (junctionSizePrint 20)
  )

  (sheet "sodonguyenly" (sheetNum 1)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible True)
        (height 7500)
        (width 9500)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 4
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 4
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (symbol (symbolRef "STM32F1_1_N") (refDesRef "STM32") (partNum 1) (pt 6000 6100) (rotation 270.0)
      (attr "RefDes" "STM32" (pt -1300 -300) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "STM32F1" (pt -1300 -2500) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "TB6612_1_N") (refDesRef "TB6612") (partNum 1) (pt 8100 6300)
      (attr "RefDes" "TB6612" (pt 400 300) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "TB6612" (pt 400 200) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "MP1584EN_1_N") (refDesRef "HAAP") (partNum 1) (pt 3000 2700) (rotation 180.0)
      (attr "RefDes" "HAAP" (pt -600 300) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "MP1584EN" (pt -600 -500) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Encoder_1_N") (refDesRef "ENL") (partNum 1) (pt 8200 4600)
      (attr "RefDes" "ENL" (pt -800 200) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Encoder" (pt -800 -600) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Encoder_1_N") (refDesRef "ENR") (partNum 1) (pt 8200 3300)
      (attr "RefDes" "ENR" (pt -800 200) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Encoder" (pt -800 -600) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin6x_1_N") (refDesRef "senR1") (partNum 1) (pt 1000 6700)
      (attr "RefDes" "senR1" (pt -400 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin6x" (pt -400 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin6x_1_N") (refDesRef "senF") (partNum 1) (pt 1000 5700)
      (attr "RefDes" "senF" (pt -400 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin6x" (pt -400 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin6x_1_N") (refDesRef "senL1") (partNum 1) (pt 1000 4700)
      (attr "RefDes" "senL1" (pt -400 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin6x" (pt -400 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin6x_1_N") (refDesRef "senR") (partNum 1) (pt 2200 6700)
      (attr "RefDes" "senR" (pt -400 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin6x" (pt -400 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin6x_1_N") (refDesRef "senL") (partNum 1) (pt 2200 5700)
      (attr "RefDes" "senL" (pt -400 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin6x" (pt -400 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin4x_1_N") (refDesRef "UART") (partNum 1) (pt 2200 4600)
      (attr "RefDes" "UART" (pt -400 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin4x" (pt -400 -200) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin_1_N") (refDesRef "Pin?") (partNum 1) (pt 1600 3100) (rotation 270.0)
      (attr "RefDes" "Pin?" (pt -100 600) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin" (pt -100 -120) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Pin_1_N") (refDesRef "Pin?") (partNum 1) (pt 1100 3100) (rotation 270.0)
      (attr "RefDes" "Pin?" (pt -100 600) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Pin" (pt -100 -120) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Switch_1_N") (refDesRef "Sw?") (partNum 1) (pt 1600 2700) (rotation 270.0)
      (attr "RefDes" "Sw?" (pt -200 0) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Switch" (pt -200 -720) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 1100 3100) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 2100 2900) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 1400 4300) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 4400 3800) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 8700 3800) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 7100 6700) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 3600 2900) (rotation 270.0) )
    (symbol (symbolRef "ECA1CHG471B_1_N") (refDesRef "C?") (partNum 1) (pt 8700 6800)
      (attr "RefDes" "C?" (pt -46.181 -210) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Price" "None" (pt -120 110) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "ECA1CHG471B" (pt -120 110) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Availability" "Unavailable" (pt -120 110) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "None" (pt -120 110) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ECA1CHG471B" (pt -120 110) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "ECA1CHG471B_1_N") (refDesRef "C?") (partNum 1) (pt 1800 3100)
      (attr "RefDes" "C?" (pt -46.181 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Price" "None" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "ECA1CHG471B" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Availability" "Unavailable" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "None" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ECA1CHG471B" (pt -46.181 -210) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 2000 3100) (rotation 90.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 8900 6800) (rotation 0.0) )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "CML") (partNum 1) (pt 7000 4400) (rotation 90.0)
      (attr "RefDes" "CML" (pt 75.073 0) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 75.073 -100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "CMR") (partNum 1) (pt 7000 3100) (rotation 90.0)
      (attr "RefDes" "CMR" (pt 75.073 0) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 75.073 -100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "C2") (partNum 1) (pt 2300 6500)
      (attr "RefDes" "C2" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "C4") (partNum 1) (pt 1100 6500)
      (attr "RefDes" "C4" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "C6") (partNum 1) (pt 1100 5500)
      (attr "RefDes" "C6" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "C8") (partNum 1) (pt 1100 4500)
      (attr "RefDes" "C8" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "C10") (partNum 1) (pt 2300 5500)
      (attr "RefDes" "C10" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "C11") (partNum 1) (pt 8400 7100) (rotation 90.0)
      (attr "RefDes" "C11" (pt 75.073 0) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (pt -75 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 75.073 -100) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SW4_1_N") (refDesRef "SW1") (partNum 1) (pt 6400 5600)
      (attr "RefDes" "SW1" (pt -210 160) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "Button chip 4 pin" (pt -420 160) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SW" (pt -210 -130) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "CER") (partNum 1) (pt 8000 3000)
      (attr "RefDes" "CER" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SR211C104KARTR1_1_N") (refDesRef "CEL") (partNum 1) (pt 8000 4300)
      (attr "RefDes" "CEL" (pt 0 75) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SnapEDA_Link" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=snap" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "Radial AVX Interconnect / Elco" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "AVX" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "SR211C104KARTR1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Check_prices" "https://www.snapeda.com/parts/SR211C104KARTR1/AVX/view-part/?ref=eda" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SR211C104KARTR1" (pt 0 -175.073) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "SW4_1_N") (refDesRef "SW1") (partNum 1) (pt 6400 5200)
      (attr "RefDes" "SW1" (pt -210 160) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "Button chip 4 pin" (pt -520 -250) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "SW" (pt -210 -130) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 7000 5500) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 5500 5600) (rotation 0.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND") (partNum 1) (pt 2600 6300) (rotation 270.0) )
  )
  (schematicPrintSettings
    (sheetList
      (sheetRef 2)
    )
  )
  (programState
    (gridState
      (currentAbsGrid "100mil")
      (currentRelGrid "100mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "(Default)")
  )
)
